Repository privacy-scaling-explorations/bandada, pull requests merged in 2022-11, with the labels that each got.

#42 SQLite support
  .env.example
  apps/api/src/app/accounts/account.module.ts
  apps/api/src/app/accounts/account.service.ts
  apps/api/src/app/accounts/entities/account.entity.ts
  apps/api/src/app/app.module.ts
  apps/api/src/app/auth/auth.service.ts
  apps/api/src/app/groups/entities/group.entity.ts
  apps/api/src/app/groups/groups.controller.ts
  apps/api/src/app/groups/groups.service.spec.ts
  apps/api/src/app/groups/groups.service.ts
  apps/api/src/app/invites/entities/invite.entity.ts
  apps/api/src/app/invites/invites.service.spec.ts
  apps/api/src/app/invites/invites.service.ts
  package.json
  yarn.lock
Labels: refactoring :recycle:

#33 zk-groups smart contract
  .env.example
  .gitignore
  contracts/README.md
  contracts/contracts/IZKGroups.sol
  contracts/contracts/ZKGroups.sol
  contracts/deployed-contracts/arbitrum.json
  contracts/deployed-contracts/goerli.json
  contracts/hardhat.config.ts
  contracts/package.json
  contracts/scripts/utils.ts
  contracts/tasks/deploy-zk-groups.ts
  contracts/test/ZKGroups.ts
  contracts/test/utils.ts
  contracts/tsconfig.json
  snark-artifacts/semaphore.wasm
  snark-artifacts/semaphore.zkey
Labels: feature :rocket:

#43 Temporary DB for tests
  .env.example
  apps/api/src/app/app.controller.spec.ts
  apps/api/src/app/app.controller.ts
  apps/api/src/app/app.module.ts
  apps/api/src/app/app.service.spec.ts
  apps/api/src/app/app.service.ts
  apps/api/src/app/groups/entities/group.entity.ts
  apps/api/src/app/groups/groups.controller.ts
  apps/api/src/app/groups/groups.module.ts
  apps/api/src/app/groups/groups.service.spec.ts
  apps/api/src/app/groups/groups.service.ts
  apps/api/src/app/invites/entities/invite.entity.ts
  apps/api/src/app/invites/invites.controller.ts
  apps/api/src/app/invites/invites.service.spec.ts
  apps/api/src/app/invites/invites.service.ts
  apps/api/src/app/invites/types/index.ts
Labels: refactoring :recycle:

#44 Leveraging cached groups to make APIs more efficient
  apps/api/src/app/common/utils.ts
  apps/api/src/app/groups/dto/add-member.dto.ts
  apps/api/src/app/groups/dto/update-group.dto.ts
  apps/api/src/app/groups/entities/group.entity.ts
  apps/api/src/app/groups/groups.controller.ts
  apps/api/src/app/groups/groups.service.spec.ts
  apps/api/src/app/groups/groups.service.ts
  apps/api/src/app/invites/invites.service.spec.ts
  apps/api/src/app/invites/invites.service.ts
Labels: refactoring :recycle:

#45 Common pattern for API errors
  apps/api/src/app/groups/groups.service.spec.ts
  apps/api/src/app/groups/groups.service.ts
  apps/api/src/app/invites/invites.service.spec.ts
  apps/api/src/app/invites/invites.service.ts
Labels: refactoring :recycle:

#57 Build a back-end mechanism to save the off-chain Merkle roots
  .env.example
  apps/api/src/app/groups/groups.module.ts
  apps/api/src/app/groups/groups.service.spec.ts
  apps/api/src/app/groups/groups.service.ts
  apps/api/src/app/invites/invites.service.spec.ts
  apps/api/src/onchain/contracts/ZKGroups/updateOffchainGroups.ts
  apps/api/src/onchain/contracts/getContractInstance.ts
  apps/api/src/onchain/getSigner.ts
  contract-artifacts/ZKGroups.json
  package.json
  tsconfig.base.json
  yarn.lock
Labels: Goal 4, Story point 8, feature :rocket:

#60 General refactoring
  .env.example
  apps/api/src/app/auth/auth.controller.ts
  apps/api/src/app/auth/strategies/github.strategy.ts
  apps/api/src/app/auth/strategies/reddit.strategy.ts
  apps/api/src/app/auth/strategies/twitter.strategy.ts
  apps/api/src/app/invites/invites.controller.ts
  apps/api/src/app/invites/invites.service.ts
  apps/api/src/environments/environment.prod.ts
  apps/api/src/environments/environment.ts
  apps/api/src/main.ts
  apps/client/project.json
  apps/client/src/app/app.tsx
  apps/client/src/components/navbar.tsx
  apps/client/src/environments/environment.prod.ts
  apps/client/src/environments/environment.ts
  apps/client/src/hooks/usePermissionedGroups.ts
  apps/client/src/pages/permissioned-group.tsx
  apps/client/src/types/invite.ts
  apps/client/tsconfig.json
  apps/dashboard/project.json
  apps/dashboard/src/app/app.tsx
  apps/dashboard/src/components/creat-group-modal.tsx
  apps/dashboard/src/components/group-box/group-card.tsx
  apps/dashboard/src/components/group-box/index.tsx
  apps/dashboard/src/components/invite-modal.tsx
  apps/dashboard/src/components/sso-button.tsx
  apps/dashboard/src/environments/environment.prod.ts
  apps/dashboard/src/environments/environment.ts
  apps/dashboard/src/hooks/useGroups.ts
  apps/dashboard/src/hooks/useInvites.ts
  apps/dashboard/src/hooks/useMembers.ts
  apps/dashboard/src/pages/manage.tsx
  apps/dashboard/src/pages/my-groups.tsx
  apps/dashboard/src/pages/sso.tsx
  apps/dashboard/tsconfig.json
  apps/dashboard/webpack.config.ts
  libs/utils/src/index.ts
  libs/utils/src/lib/createIdentity.ts
Labels: refactoring :recycle:

#64 Refactoring error handling with invite code
  apps/api/src/app/groups/groups.service.ts
  apps/api/src/app/invites/invites.service.spec.ts
  apps/api/src/app/invites/invites.service.ts
Labels: bug 🐛, refactoring :recycle:

#68 backend for onchain groups
  apps/api/src/app/groups/groups.service.ts
  contract-artifacts/Semaphore.json
  libs/onchain/.babelrc
  libs/onchain/.eslintrc.json
  libs/onchain/README.md
  libs/onchain/jest.config.ts
  libs/onchain/project.json
  libs/onchain/src/getBackendSigner.ts
  libs/onchain/src/getContractInstance.ts
  libs/onchain/src/index.ts
  libs/onchain/src/lib/Semaphore/onchainGroups.ts
  libs/onchain/src/lib/ZKGroups/updateOffchainGroups.ts
  libs/onchain/tsconfig.json
  libs/onchain/tsconfig.lib.json
  libs/onchain/tsconfig.spec.json
  package.json
  tsconfig.base.json
  workspace.json
  yarn.lock
Labels: Goal 4, feature :rocket:
