Repository privacy-scaling-explorations/bandada, pull requests merged in 2022-12, with the labels that each got.

#73 Update some API entity parameters
  apps/api/src/app/accounts/account.service.ts
  apps/api/src/app/accounts/entities/account.entity.ts
  apps/api/src/app/common/utils.ts
  apps/api/src/app/groups/groups.controller.ts
  apps/api/src/app/groups/groups.service.ts
  apps/api/src/app/invites/invites.controller.ts
  apps/api/src/app/invites/invites.service.ts
  apps/client/src/pages/permissioned-group.tsx
  apps/client/src/types/invite.ts
Labels: refactoring :recycle:

#65 Create on-chain groups
  apps/client/src/pages/permissioned-group.tsx
  apps/dashboard/src/app/app.tsx
  apps/dashboard/src/components/creat-group-modal.tsx
  apps/dashboard/src/components/navbar.tsx
  apps/dashboard/src/components/sso-button.tsx
  apps/dashboard/src/hooks/useEthereumWallet.ts
  apps/dashboard/src/hooks/useOffchainGroups.ts
  apps/dashboard/src/hooks/useOnchainGroups.ts
  apps/dashboard/src/hooks/useSigner.ts
  apps/dashboard/src/pages/my-groups.tsx
  apps/dashboard/src/pages/sso.tsx
  apps/dashboard/src/types/groups/index.ts
  libs/onchain/src/lib/Semaphore/onchainGroups.ts
Labels: Goal 2, Story point 8, feature :rocket:

#76 feat: add onchain-group member logic(frontend)
  apps/dashboard/src/components/add-member-modal.tsx
  apps/dashboard/src/components/group-box/group-card.tsx
  apps/dashboard/src/hooks/useOnchainGroups.ts
  apps/dashboard/src/pages/manage.tsx
  libs/onchain/src/lib/Semaphore/onchainGroups.ts
Labels: feature :rocket:

#77 refactor: use cookies for http requests only
  apps/api/src/app/auth/auth.controller.ts
  apps/dashboard/src/components/navbar.tsx
  apps/dashboard/src/pages/my-groups.tsx
Labels: refactoring :recycle:
