Repository privacy-scaling-explorations/bandada, pull requests merged in 2022-08, with the labels that each got.

#7 Members API
  apps/api/src/app/app.module.ts
  apps/api/src/app/members/dto/add-member.dto.ts
  apps/api/src/app/members/entities/member.entity.ts
  apps/api/src/app/members/members.controller.spec.ts
  apps/api/src/app/members/members.controller.ts
  apps/api/src/app/members/members.module.ts
  apps/api/src/app/members/members.service.spec.ts
  apps/api/src/app/members/members.service.ts
  apps/api/src/main.ts
  package.json
  yarn.lock
Labels: Goal 3, feature :rocket:

#6 SSO Authentication
  .env.sample
  apps/api/src/app/account/account.model.ts
  apps/api/src/app/account/account.module.ts
  apps/api/src/app/account/account.service.spec.ts
  apps/api/src/app/account/account.service.ts
  apps/api/src/app/account/dto/create-account.dto.ts
  apps/api/src/app/account/dto/update-account.dto.ts
  apps/api/src/app/app.module.ts
  apps/api/src/app/auth/auth.controller.spec.ts
  apps/api/src/app/auth/auth.controller.ts
  apps/api/src/app/auth/auth.module.ts
  apps/api/src/app/auth/auth.service.ts
  apps/api/src/app/auth/guards/github.guard.ts
  apps/api/src/app/auth/guards/twitter.guard.ts
  apps/api/src/app/auth/providers/auth-serializer.provider.ts
  apps/api/src/app/auth/strategies/github.strategy.ts
  apps/api/src/app/auth/strategies/index.ts
  apps/api/src/app/auth/strategies/twitter.strategy.ts
  apps/api/src/app/auth/type.ts
  apps/api/src/app/common/cookie.serializer.ts
  apps/api/src/app/interceptors/token.interceptors.ts
  apps/api/src/main.ts
  package.json
  yarn.lock
Labels: Goal 1, feature :rocket:

#11 Auth APIs refactoring
  .env.example
  .env.sample
  .eslintrc.json
  apps/api/src/app/account/account.service.spec.ts
  apps/api/src/app/account/dto/create-account.dto.ts
  apps/api/src/app/accounts/account.model.ts
  apps/api/src/app/accounts/account.module.ts
  apps/api/src/app/accounts/account.service.ts
  apps/api/src/app/accounts/dto/create-account.dto.ts
  apps/api/src/app/accounts/dto/update-account.dto.ts
  apps/api/src/app/app.module.ts
  apps/api/src/app/auth/auth.controller.spec.ts
  apps/api/src/app/auth/auth.controller.ts
  apps/api/src/app/auth/auth.module.ts
  apps/api/src/app/auth/auth.service.ts
  apps/api/src/app/auth/guards/github.guard.ts
  apps/api/src/app/auth/guards/twitter.guard.ts
  apps/api/src/app/auth/providers/auth-serializer.provider.ts
  apps/api/src/app/auth/strategies/github.strategy.ts
  apps/api/src/app/auth/strategies/index.ts
  apps/api/src/app/auth/strategies/twitter.strategy.ts
  apps/api/src/app/auth/type.ts
  apps/api/src/app/interceptors/token.interceptors.ts
  apps/api/src/main.ts
  package.json
  tsconfig.base.json
  yarn.lock
Labels: Goal 1, refactoring :recycle:

#17 Reddit Passport strategy
  .env.example
  apps/.gitkeep
  apps/api/src/app/accounts/account.model.ts
  apps/api/src/app/accounts/dto/create-account.dto.ts
  apps/api/src/app/auth/auth.controller.ts
  apps/api/src/app/auth/auth.module.ts
  apps/api/src/app/auth/strategies/reddit.strategy.ts
  apps/api/src/app/auth/type.ts
  apps/api/src/app/auth/types.ts
  libs/.gitkeep
  libs/passport-reddit/.babelrc
  libs/passport-reddit/.eslintrc.json
  libs/passport-reddit/README.md
  libs/passport-reddit/jest.config.ts
  libs/passport-reddit/project.json
  libs/passport-reddit/src/index.ts
  libs/passport-reddit/src/lib/passport-reddit.ts
  libs/passport-reddit/src/lib/types.ts
  libs/passport-reddit/tsconfig.json
  libs/passport-reddit/tsconfig.lib.json
  libs/passport-reddit/tsconfig.spec.json
  package.json
  tsconfig.base.json
  workspace.json
  yarn.lock
Labels: Goal 1, feature :rocket:
