Repository privacy-scaling-explorations/bandada, pull requests merged in 2023-02, with the labels that each got.

#112 Refactor auth flow
  apps/api/src/app/auth/auth.controller.ts
  apps/dashboard/src/components/group-box/index.tsx
  apps/dashboard/src/components/navbar.tsx
  apps/dashboard/src/hooks/useOnchainGroups.ts
  apps/dashboard/src/pages/my-groups.tsx
  apps/dashboard/src/pages/sso.tsx
Labels: refactoring :recycle:

#114 Auto refresh group list upon creating a new group
  apps/dashboard/src/components/add-member-modal.tsx
  apps/dashboard/src/components/create-group-modal.tsx
  apps/dashboard/src/pages/my-groups.tsx
Labels: feature :rocket:

#115 Add option to connect to multiple wallets
  apps/dashboard/project.json
  apps/dashboard/src/app/app.tsx
  apps/dashboard/src/components/add-member-modal.tsx
  apps/dashboard/src/components/create-group-modal.tsx
  apps/dashboard/src/components/navbar.tsx
  apps/dashboard/src/hooks/useEthereumWallet.ts
  apps/dashboard/src/hooks/useSigner.ts
  apps/dashboard/src/main.tsx
  apps/dashboard/src/pages/my-groups.tsx
  apps/dashboard/src/pages/sso.tsx
  apps/dashboard/src/polyfills.ts
  package.json
  yarn.lock
Labels: feature :rocket:, refactoring :recycle:

#117 ZKGroups contract independent from protocols
  apps/api/src/app/groups/groups.service.ts
  apps/contracts/contracts/IZKGroups.sol
  apps/contracts/contracts/ZKGroups.sol
  apps/contracts/contracts/protocols/IZKGroupsSemaphore.sol
  apps/contracts/contracts/protocols/ZKGroupsSemaphore.sol
  apps/contracts/hardhat.config.ts
  apps/contracts/project.json
  apps/contracts/tasks/deploy-zkgroups-semaphore.ts
  apps/contracts/tasks/deploy-zkgroups.ts
  apps/contracts/test/ZKGroups.ts
  apps/contracts/test/ZKGroupsSemaphore.ts
  contract-artifacts/ZKGroups.json
  libs/contract-utils/src/networks.ts
  libs/contract-utils/src/zkGroups.ts
  yarn.lock
Labels: refactoring :recycle:

#120 Refactoring on code to update zk-groups contract groups
  apps/api/src/app/groups/groups.service.ts
Labels: refactoring :recycle:

#122 Hardhat plugin
  LICENSE
  README.md
  apps/contracts/test/ZKGroupsSemaphore.ts
  libs/hardhat/.babelrc
  libs/hardhat/.eslintrc.json
  libs/hardhat/README.md
  libs/hardhat/jest.config.ts
  libs/hardhat/package.json
  libs/hardhat/project.json
  libs/hardhat/src/index.ts
  libs/hardhat/src/tasks/deploy-zk-groups-semaphore.ts
  libs/hardhat/src/tasks/deploy-zk-groups.ts
  libs/hardhat/tsconfig.json
  libs/hardhat/tsconfig.lib.json
  libs/hardhat/tsconfig.spec.json
  package.json
  tools/scripts/publish.mjs
  tsconfig.base.json
  workspace.json
  yarn.lock
Labels: feature :rocket:

#125 Automatic releases
  .commitlintrc.json
  .github/workflows/coverall.yml
  .github/workflows/release.yml
  .github/workflows/style.yml
  .github/workflows/test.yml
  .husky/commit-msg
  CONTRIBUTING.md
  apps/api/Dockerfile
  apps/api/project.json
  apps/client/Dockerfile
  apps/client/project.json
  apps/contracts/contracts/package.json
  apps/contracts/project.json
  apps/dashboard/Dockerfile
  apps/dashboard/project.json
  libs/hardhat/package.json
  libs/hardhat/project.json
  package.json
  tools/scripts/bump-version.mjs
  tools/scripts/publish-version.mjs
  tools/scripts/publish.mjs
  yarn.lock
Labels: devops :wrench:

#128 Chore/test coverage
  .github/workflows/coverall.yml
  apps/api/project.json
  apps/client/jest.config.ts
  apps/client/project.json
  apps/contracts/.solcover.js
  apps/contracts/hardhat.config.ts
  apps/contracts/project.json
  apps/dashboard/project.json
  libs/contract-utils/jest.config.ts
  libs/contract-utils/project.json
  libs/hardhat/jest.config.ts
  libs/hardhat/project.json
  libs/passport-reddit/jest.config.ts
  libs/passport-reddit/project.json
  libs/utils/jest.config.ts
  libs/utils/project.json
  package.json
  yarn.lock
Labels: devops :wrench:

#132 chore: add env to readme
  README.md
Labels: documentation :book:

#133 Remove express/session
  README.md
  apps/api/.env.sample
  apps/api/src/main.ts
  docker-compose.yml
  package.json
  yarn.lock
Labels: dependencies :package:

#137 Add separate DB table for members
  apps/api/src/app/groups/entities/group.entity.ts
  apps/api/src/app/groups/entities/member.entity.ts
  apps/api/src/app/groups/group.utils.ts
  apps/api/src/app/groups/groups.controller.ts
  apps/api/src/app/groups/groups.module.ts
  apps/api/src/app/groups/groups.service.spec.ts
  apps/api/src/app/groups/groups.service.ts
  apps/api/src/app/invites/invites.service.spec.ts
  database/seed.sql
Labels: refactoring :recycle:

#141 Refactor routes to use groupId instead of groupName
  apps/api/src/app/groups/entities/group.entity.ts
  apps/api/src/app/groups/group.utils.ts
  apps/api/src/app/groups/groups.controller.ts
  apps/api/src/app/groups/groups.service.test.ts
  apps/api/src/app/groups/groups.service.ts
  apps/api/src/app/invites/dto/create-invite.dto.ts
  apps/api/src/app/invites/invites.service.test.ts
  apps/api/src/app/invites/invites.service.ts
  apps/client/src/hooks/usePermissionedGroups.ts
  apps/client/src/pages/permissioned-group.tsx
  apps/dashboard/src/app/app.tsx
  apps/dashboard/src/components/create-group-modal.tsx
  apps/dashboard/src/components/group-box/group-card.tsx
  apps/dashboard/src/components/invite-modal.tsx
  apps/dashboard/src/hooks/useInvites.ts
  apps/dashboard/src/hooks/useMembers.ts
  apps/dashboard/src/hooks/useOnchainGroups.ts
  apps/dashboard/src/pages/manage.tsx
  apps/dashboard/src/types/groups/index.ts
Labels: refactoring :recycle:

#142 Fix docker config to work with yarn workspace
  .dockerignore
  apps/api/Dockerfile
  apps/client/Dockerfile
  apps/dashboard/Dockerfile
Labels: devops :wrench:
