Repository privacy-scaling-explorations/bandada, pull requests merged in 2023-08, with the labels that each got.

#241 Small improvements and bug fixes
  apps/api/package.json
  apps/api/src/app/app.module.ts
  apps/api/src/app/groups/dto/update-group.dto.ts
  apps/api/src/app/groups/groups.controller.ts
  apps/api/src/app/groups/groups.service.ts
  apps/api/src/app/invites/invites.controller.ts
  apps/api/src/app/invites/invites.service.ts
  apps/dashboard/src/api/bandadaAPI.ts
  apps/dashboard/src/components/add-member-modal.tsx
  apps/dashboard/src/components/create-group-modal.tsx
  apps/dashboard/src/pages/group.tsx
  apps/dashboard/src/utils/shortenNumber.ts
  yarn.lock
Labels: bug 🐛, feature :rocket:

#252 Update API Docs in Add Member function
  apps/api/src/app/groups/groups.controller.ts
Labels: documentation :book:

#249 Uncomment postgres from docker compose
  docker-compose.yml
Labels: devops :wrench:

#253 More test coverage on services and libraries
  apps/api/src/app/auth/auth.controller.ts
  apps/api/src/app/auth/auth.guard.ts
  apps/api/src/app/auth/auth.service.test.ts
  apps/api/src/app/auth/auth.service.ts
  apps/api/src/app/auth/dto/siwe.dto.ts
  apps/api/src/app/groups/groups.controller.ts
  apps/api/src/app/groups/groups.service.test.ts
  apps/api/src/app/groups/groups.service.ts
  apps/api/src/app/groups/groups.utils.test.ts
  apps/api/src/app/invites/invites.service.test.ts
  apps/api/src/app/reputation/reputation.service.test.ts
  apps/api/src/app/reputation/reputation.service.ts
  jest.config.ts
  libs/api-sdk/src/groups.ts
  libs/reputation/src/index.test.ts
  libs/reputation/src/testUtils.ts
Labels: tests :test_tube:

#257 Add invites in API SDK
  apps/api/src/app/groups/docSchemas/groupResponse.ts
  apps/api/src/app/groups/docSchemas/index.ts
  apps/api/src/app/groups/docSchemas/inviteResponse.ts
  apps/api/src/app/invites/invites.controller.ts
  libs/api-sdk/src/config.ts
  libs/api-sdk/src/groups.ts
  libs/api-sdk/src/index.test.ts
  libs/api-sdk/src/index.ts
  libs/api-sdk/src/invites.ts
  libs/api-sdk/src/types/index.ts
Labels: feature :rocket:

#259 Add Waiter services stable in a loop
  .github/scripts/deploy.sh
Labels: devops :wrench:

#256 New client app design
  apps/api/package.json
  apps/client/index.html
  apps/client/package.json
  apps/client/src/app.tsx
  apps/client/src/assets/.gitkeep
  apps/client/src/assets/favicon.ico
  apps/client/src/assets/icon1.svg
  apps/client/src/components/navbar.tsx
  apps/client/src/hooks/usePermissionedGroups.ts
  apps/client/src/hooks/useSigner.ts
  apps/client/src/main.tsx
  apps/client/src/pages/home.tsx
  apps/client/src/pages/permissioned-group.tsx
  apps/client/src/routes.tsx
  apps/client/src/styles/colors.ts
  apps/client/src/styles/components/button.ts
  apps/client/src/styles/components/index.ts
  apps/client/src/styles/index.ts
  apps/client/src/styles/styles.ts
  apps/client/src/types/group.ts
  apps/client/src/types/index.ts
  apps/client/src/types/invite.ts
  apps/contracts/contracts/package.json
  apps/dashboard/.env.local
  apps/dashboard/.env.production
  apps/dashboard/package.json
  apps/dashboard/src/api/bandadaAPI.ts
  libs/api-sdk/package.json
  libs/hardhat/package.json
  libs/reputation/package.json
  libs/utils/package.json
  yarn.lock
Labels: refactoring :recycle:

#261 Update production domain
  README.md
  apps/client/.env.production
  apps/contracts/contracts/README.md
  apps/dashboard/.env.production
  libs/api-sdk/README.md
  libs/api-sdk/src/config.ts
  libs/hardhat/README.md
  libs/reputation/README.md
  libs/utils/README.md
Labels: devops :wrench:

#264 feat(api-sdk): add custom domain in the api sdk
  libs/api-sdk/src/apiSdk.ts
  libs/api-sdk/src/checkParameter.ts
  libs/api-sdk/src/config.ts
  libs/api-sdk/src/groups.ts
  libs/api-sdk/src/index.test.ts
  libs/api-sdk/src/index.ts
  libs/api-sdk/src/invites.ts
  libs/api-sdk/src/types/index.ts
Labels: feature :rocket:

#266 API lib to the client app
  apps/api/package.json
  apps/client/package.json
  apps/client/src/pages/home.tsx
  apps/client/src/utils/api.ts
  apps/contracts/contracts/package.json
  apps/dashboard/package.json
  apps/dashboard/src/hooks/use-session-data.ts
  libs/api-sdk/package.json
  libs/api-sdk/src/apiSdk.ts
  libs/api-sdk/src/groups.ts
  libs/api-sdk/src/invites.ts
  libs/api-sdk/src/types/index.ts
  libs/credentials/package.json
  libs/hardhat/package.json
  libs/utils/package.json
  yarn.lock
Labels: refactoring :recycle:
