Repository privacy-scaling-explorations/bandada, pull requests merged in 2023-05, with the labels that each got.

#193 Update DB Schema
  apps/api/src/app/admins/entities/admin.entity.ts
  apps/api/src/app/groups/dto/create-group.dto.ts
  apps/api/src/app/groups/dto/update-group.dto.ts
  apps/api/src/app/groups/entities/group.entity.ts
  apps/api/src/app/groups/entities/member.entity.ts
  apps/api/src/app/groups/entities/reputation-account.entity.ts
  apps/api/src/app/groups/groups.controller.ts
  apps/api/src/app/groups/groups.module.ts
  apps/api/src/app/groups/groups.service.ts
  apps/api/src/app/groups/groups.utils.ts
  apps/api/src/app/invites/entities/invite.entity.ts
  apps/api/src/app/invites/invites.service.test.ts
  apps/api/src/app/invites/invites.service.ts
  apps/api/zk-groups.db
  apps/client/src/pages/permissioned-group.tsx
  apps/client/src/types/invite.ts
  database/seed.sql
Labels: feature :rocket:, refactoring :recycle:

#194 Add API for Reputation Criteria
  apps/api/src/app/groups/dto/update-group.dto.ts
  apps/api/src/app/groups/groups.service.test.ts
  apps/api/src/app/groups/groups.service.ts
  apps/api/src/app/groups/groups.utils.ts
Labels: feature :rocket:

#196 API to add members manually & to get admin groups
  apps/api/src/app/groups/groups.controller.ts
  apps/api/src/app/groups/groups.service.test.ts
  apps/api/src/app/groups/groups.service.ts
  apps/dashboard/src/api/bandadaAPI.ts
  apps/dashboard/src/components/navbar.tsx
  apps/dashboard/src/context/auth-context.tsx
  apps/dashboard/src/pages/groups.tsx
  apps/dashboard/src/utils/session.ts
Labels: feature :rocket:

#199 General refactoring
  .eslintrc.json
  README.md
  apps/api/.env.example
  apps/api/package.json
  apps/api/src/app/groups/groups.service.ts
  apps/dashboard/.env.local
  apps/dashboard/.env.production
  apps/dashboard/package.json
  apps/dashboard/src/api/bandadaAPI.ts
  apps/dashboard/src/api/semaphoreAPI.ts
  apps/dashboard/src/components/create-group-modal.tsx
  apps/dashboard/src/components/group-box/index.tsx
  apps/dashboard/src/components/group-card.tsx
  apps/dashboard/src/components/invite-modal.tsx
  apps/dashboard/src/components/navbar.tsx
  apps/dashboard/src/context/auth-context.tsx
  apps/dashboard/src/data/groupSizes.ts
  apps/dashboard/src/data/index.ts
  apps/dashboard/src/hooks/use-session-data.ts
  apps/dashboard/src/main.tsx
  apps/dashboard/src/pages/group.tsx
  apps/dashboard/src/pages/groups.tsx
  apps/dashboard/src/polyfills.ts
  apps/dashboard/src/routes.tsx
  apps/dashboard/src/types/Admin.ts
  apps/dashboard/src/types/Group.ts
  apps/dashboard/src/types/groups/index.ts
  apps/dashboard/src/types/index.ts
  apps/dashboard/src/utils/parseGroupName.ts
  apps/dashboard/src/utils/session.ts
  yarn.lock
Labels: refactoring :recycle:
