Repository privacy-scaling-explorations/bandada, pull requests merged in 2023-03, with the labels that each got.

#145 Simple homepage and general refactoring
  .eslintrc.json
  apps/api/src/app/auth/auth.controller.ts
  apps/dashboard/src/api/semaphoreAPI.ts
  apps/dashboard/src/api/zkGroupsAPI.ts
  apps/dashboard/src/app.tsx
  apps/dashboard/src/components/create-group-modal.tsx
  apps/dashboard/src/components/invite-modal.tsx
  apps/dashboard/src/components/navbar.tsx
  apps/dashboard/src/hooks/useInvites.ts
  apps/dashboard/src/hooks/useMembers.ts
  apps/dashboard/src/hooks/useOffchainGroups.ts
  apps/dashboard/src/hooks/useOnchainGroups.ts
  apps/dashboard/src/main.tsx
  apps/dashboard/src/pages/home.tsx
  apps/dashboard/src/pages/manage.tsx
  apps/dashboard/src/pages/my-groups.tsx
  apps/dashboard/src/pages/sso.tsx
Labels: feature :rocket:, refactoring :recycle:

#152 Update off-chain group fingerprint without delay
  apps/api/src/app/groups/groups.service.test.ts
  apps/api/src/app/groups/groups.service.ts
  apps/api/src/app/invites/invites.service.test.ts
Labels: refactoring :recycle:

#154 Add remove members functionality for off-chain groups
  apps/api/src/app/groups/groups.controller.ts
  apps/api/src/app/groups/groups.service.test.ts
  apps/api/src/app/groups/groups.service.ts
  apps/dashboard/src/api/zkGroupsAPI.ts
  apps/dashboard/src/pages/manage.tsx
Labels: feature :rocket:

#155 New Homepage
  apps/dashboard/index.html
  apps/dashboard/package.json
  apps/dashboard/src/assets/.gitkeep
  apps/dashboard/src/assets/favicon.ico
  apps/dashboard/src/assets/logo.svg
  apps/dashboard/src/main.tsx
  apps/dashboard/src/pages/home.tsx
  apps/dashboard/src/pages/sso.tsx
  apps/dashboard/src/styles/components/button.ts
  apps/dashboard/src/styles/index.ts
  yarn.lock
Labels: design :art:, feature :rocket:

#157 Selection of files to be tested
  apps/api/src/app/accounts/account.service.ts
  apps/api/src/app/auth/auth.module.ts
  apps/api/src/app/auth/auth.service.ts
  apps/api/src/app/auth/strategies/reddit.strategy.ts
  apps/api/src/app/groups/groups.controller.ts
  apps/api/src/app/groups/groups.service.ts
  apps/api/src/app/groups/groups.utils.test.ts
  apps/api/src/app/groups/groups.utils.ts
  apps/api/src/app/invites/invites.controller.ts
  apps/api/src/app/utils/cookie.serializer.ts
  apps/api/src/app/utils/index.test.ts
  apps/api/src/app/utils/index.ts
  apps/api/src/app/utils/passportReddit.ts
  apps/api/tsconfig.json
  jest.config.ts
  libs/utils/src/contractAddresses.ts
  libs/utils/src/contractArtifacts/Semaphore.json
  libs/utils/src/contractArtifacts/ZKGroups.json
  libs/utils/src/getContract.ts
  libs/utils/src/getProvider.ts
  libs/utils/src/getSemaphoreContract.ts
  libs/utils/src/getWallet.ts
  libs/utils/src/getZKGroupsContract.ts
  libs/utils/src/index.ts
  libs/utils/src/request.ts
Labels: tests :test_tube:

#158 Separation of env secret variables
  apps/api/.env.example
  apps/api/package.json
  apps/api/src/app/app.module.ts
  apps/api/src/app/auth/strategies/github.strategy.ts
  apps/api/src/app/auth/strategies/reddit.strategy.ts
  apps/api/src/app/auth/strategies/twitter.strategy.ts
  apps/api/src/app/groups/groups.service.ts
  apps/client/.env.local
  apps/client/.env.production
  apps/client/package.json
  apps/contracts/contracts/package.json
  apps/contracts/package.json
  apps/dashboard/.env.local
  apps/dashboard/.env.production
  apps/dashboard/package.json
  apps/dashboard/src/api/semaphoreAPI.ts
  libs/hardhat/package.json
  yarn.lock
Labels: dependencies :package:, devops :wrench:

#168 Rename to Bandada in AWS scripts
  .github/scripts/build.sh
  .github/scripts/deploy.sh
  .github/workflows/deploy.yml
  README.md
  appspec.yml
  docker-compose.prod.yml
  scripts/after_install.sh
  scripts/start_app.sh
  scripts/stop_app.sh
  scripts/validate_app.sh
Labels: devops :wrench:

#175 Minor bugs
  apps/api/package.json
  apps/api/src/app/accounts/entities/account.entity.ts
  apps/api/src/app/groups/groups.controller.ts
  apps/api/src/app/groups/groups.service.ts
  apps/api/src/app/invites/invites.controller.ts
  apps/api/src/main.ts
  apps/dashboard/src/main.tsx
  database/seed.sql
  yarn.lock
Labels: bug 🐛
